Add config app and CommunityPage model for local discussion pages
WikipediaLibrary/TWLight pull request #1199
Opened 2023-09-09 15:41 UTC by Samwalton9

[//]: # (Thank you for uploading a PR to the Wikipedia Library!)

## Description
Per https://phabricator.wikimedia.org/T299510, we wanted to add a community page link depending on the user's language code. Non-technical WMF staff want to be able to add new community pages and associate them with a language.

I figure there were probably a few different approaches we could have taken here. The option I went for was to add a new app, `config`, and define a `CommunityPage` model there for this data. My rationale was that we might want to use the `config` app for other site-wide configuration models, which are more accessible to non-developers than requiring a config file to be updated via a pull request. I appreciate this comes with a technical overhead tradeoff, though. I'm very happy to hear feedback on whether this was a sensible approach or not and rework accordingly.

There's still work to do here, I think, namely tests. I didn't want to go too far before getting feedback on the approach.

## Rationale
Laid out in https://phabricator.wikimedia.org/T299510.

## Phabricator Ticket
https://phabricator.wikimedia.org/T299510

## How Has This Been Tested?
Local testing with languages that have and have not been defined. I didn't write any tests yet because I wanted to get feedback on the approach.

## Screenshots of your changes (if appropriate):
<img width="307" alt="Screenshot 2023-09-09 at 16 38 05" src="https://github.com/WikipediaLibrary/TWLight/assets/12038840/97cde0c1-ba31-484b-b782-953390ab80a2">

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Minor change (fix a typo, add a translation tag, add section to README, etc.)

2023-09-09 15:47 UTC, Samwalton9 commented on TWLight/users/templates/users/filter_section.html
> +          {% trans "Learn more" %}</a>
Just a note that I moved these </a>s to prevent the underline from straying into whitespace.

2023-09-09 15:51 UTC, Samwalton9 commented
An initial followup thought: Maybe a `config` app is overkill for this one `CommunityPage` model, and it should have just lived in the `users` app since it's only used within the context of that app.

2023-11-18 04:18 UTC, suecarmol requested changes
Thank you for addressing this problem Sam! While your approach was sound, I think I found a better one in 1224. Let me know what you think!

2023-12-23 13:37 UTC, closed without merging

2023-12-23 13:37 UTC, Samwalton9 commented
Closing in favour of https://github.com/WikipediaLibrary/TWLight/pull/1224.