Remove Occupation field & data
WikipediaLibrary/TWLight pull request #1288
Opened 2024-05-06 19:54 UTC by Samwalton9

[//]: # (Thank you for uploading a PR to the Wikipedia Library!)

## Description
Per https://phabricator.wikimedia.org/T363831, we have no active partners using this data and do not expect to have any in the future (we would now push back strongly on collecting this information). This PR removes occupation fields, data, and use in both user and application views.

## Phabricator Ticket
[T363831](https://phabricator.wikimedia.org/T363831)

## How Has This Been Tested?
Tests pass (after a couple of minor adjustments). Running migrations did blow up my local environment for reasons that weren't clear to me, so worth double checking the new migrations don't cause issues.

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Minor change (fix a typo, add a translation tag, add section to README, etc.)

2024-05-28 16:27 UTC, Samwalton9 commented on TWLight/resources/admin.py
> +    search_fields = ("partners", "phabricator_task")
I've just spotted this entirely unrelated test I was doing that I accidentally committed here.

2024-05-28 16:32 UTC, Samwalton9 commented on TWLight/resources/admin.py
> +    search_fields = ("partners", "phabricator_task")
Removed this, squashed, and force pushed :)

2024-06-17 18:52 UTC, katydidnot requested changes
Thanks for your work on this Sam! 
I was able to pull your code down and test it out. 

I'm seeing a lot of MySQL errors when I run the tests: 
`MySQLdb.IntegrityError: (1364, "Field 'occupation' doesn't have a default value")`

I'm thinking we will probably want some kind of db migration to either set a default value, or to just delete the column all together.

2024-06-18 19:31 UTC, Samwalton9 commented
> Thanks for your work on this Sam! I was able to pull your code down and test it out.
> 
> I'm seeing a lot of MySQL errors when I run the tests: `MySQLdb.IntegrityError: (1364, "Field 'occupation' doesn't have a default value")`
> 
> I'm thinking we will probably want some kind of db migration to either set a default value, or to just delete the column all together.

Is this still the case when you run migrations locally? As I understand it CI should handle that step for us for production, but locally you still need to manually run migrations to get the column dropped.

2024-06-21 15:11 UTC, katydidnot commented
> > Thanks for your work on this Sam! I was able to pull your code down and test it out.
> > I'm seeing a lot of MySQL errors when I run the tests: `MySQLdb.IntegrityError: (1364, "Field 'occupation' doesn't have a default value")`
> > I'm thinking we will probably want some kind of db migration to either set a default value, or to just delete the column all together.
> 
> Is this still the case when you run migrations locally? As I understand it CI should handle that step for us for production, but locally you still need to manually run migrations to get the column dropped.

Yes, and when I try to run the migrations I get the following error: 
` File "/venv/lib/python3.11/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1364, "Field 'occupation' doesn't have a default value")`

2024-06-25 01:01 UTC, suecarmol commented
> > > Thanks for your work on this Sam! I was able to pull your code down and test it out.
> > > I'm seeing a lot of MySQL errors when I run the tests: `MySQLdb.IntegrityError: (1364, "Field 'occupation' doesn't have a default value")`
> > > I'm thinking we will probably want some kind of db migration to either set a default value, or to just delete the column all together.
> > 
> > 
> > Is this still the case when you run migrations locally? As I understand it CI should handle that step for us for production, but locally you still need to manually run migrations to get the column dropped.
> 
> Yes, and when I try to run the migrations I get the following error:
> 
> ```
>     _mysql.connection.query(self, query)
> django.db.utils.IntegrityError: (1364, "Field 'occupation' doesn't have a default value")
> ```



> > > Thanks for your work on this Sam! I was able to pull your code down and test it out.
> > > I'm seeing a lot of MySQL errors when I run the tests: `MySQLdb.IntegrityError: (1364, "Field 'occupation' doesn't have a default value")`
> > > I'm thinking we will probably want some kind of db migration to either set a default value, or to just delete the column all together.
> > 
> > 
> > Is this still the case when you run migrations locally? As I understand it CI should handle that step for us for production, but locally you still need to manually run migrations to get the column dropped.
> 
> Yes, and when I try to run the migrations I get the following error:
> 
> ```
>     _mysql.connection.query(self, query)
> django.db.utils.IntegrityError: (1364, "Field 'occupation' doesn't have a default value")
> ```

I think this might be an issue with your local environment. This is working for me. We can take a look at it on our engineering meeting or another time!

2024-06-25 01:02 UTC, suecarmol approved these changes
I checked this in my local environment and everything seems to be working. Thanks for removing this unused field!

2024-06-25 01:02 UTC, merged