Anchored the Library bundle 'Learn More' button to the Library Bundle…
WikipediaLibrary/TWLight pull request #541
Opened 2020-10-02 11:26 UTC by Rahul-3000

… section of the About page

[//]: # (Thank you for uploading a PR to the Wikipedia Library!)

## Description
When a user was clicking on the Learn More button in the Library Bundle information box, instead of taking to that section it used to take it to about page only. SO I wrote the code so it will navigate to the Library bundle section on the About page.

## Phabricator Ticket
[//]: #  https://phabricator.wikimedia.org/T252511

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2020-10-06 21:53 UTC, suecarmol requested changes
Thank you for your contribution! This is looking great, I just need you to make some changes before I go ahead and merge this.

2020-10-06 21:53 UTC, suecarmol commented on TWLight/templates/home.html
> +{#          need to edit this#}
Could you please remove this line as well?

2020-10-06 21:53 UTC, suecarmol commented on TWLight/templates/home.html
> +{#need to edit line 90 for about#}
This line needs to be removed

2020-10-06 21:53 UTC, suecarmol commented on TWLight/templates/about.html
> +  <h3 id="anchor">Library Bundle</h3>
The name of the id does not indicate what it's identifying. I suggest changing the id name to `bundle-section`

2020-12-02 15:07 UTC, jsnshrmn commented
Closing due to lack of activity.

2020-12-02 15:07 UTC, closed without merging