Added a withdraw button which withdraw/delete the application
WikipediaLibrary/TWLight pull request #542
Opened 2020-10-07 17:19 UTC by YashAgrawal9265

[//]: # (Thank you for uploading a PR to the Wikipedia Library!)

## Description
I had created a withdraw button which withdraw the application and redirect user to the home page.
When user will click on the button the application will be deleted and user will redirect to the home page
with a message as shown in the figure..

<img width="960" alt="2020-10-07" src="https://user-images.githubusercontent.com/69956695/95364597-a6e20100-08ee-11eb-9aa5-ad46a484c36b.png">

## Rationale
[//]: # (Why is this change required? What problem does it solve?)

## Phabricator Ticket
 https://phabricator.wikimedia.org/T243137

## How Has This Been Tested?
[//]: # (- Did you add tests to your changes? Did you modify tests to accommodate your changes?)
[//]: # (- Can this change be tested manually? How?)

## Screenshots of your changes (if appropriate):
<img width="960" alt="2020-10-07 (2)" src="https://user-images.githubusercontent.com/69956695/95365119-5028f700-08ef-11eb-8bcd-14a4aa6e3500.png">
   
## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2020-10-23 00:31 UTC, suecarmol requested changes
Thank you for your contribution to The Wikipedia Library project! There are a few changes that need to be made to this PR in order to merge this. The main change you need to make is, instead of deleting the application, you should update the status to `Invalid`.

2020-10-23 00:31 UTC, suecarmol commented on TWLight/users/urls.py
> +        name="my_deletion",
Can you change `my_deletion` to `withdraw`?

2020-10-23 00:31 UTC, suecarmol commented on TWLight/users/views.py
> +class DeleteApplication(RedirectView):
Instead of `DeleteApplication`, can you change the class name to `WithdrawApplication` since we do not want to delete the application?

2020-10-23 00:31 UTC, suecarmol commented on TWLight/users/views.py
> +        Application.objects.get(pk=del_id).delete()
Change this statement to 

```python
Application.objects.get(pk=del_id).update(status=Application.INVALID)
```

2020-10-23 00:31 UTC, suecarmol commented on TWLight/users/views.py
> +        del_id = kwargs["id"]
Change this variable name, since we are no longer deleting the application.

2020-10-23 05:34 UTC, YashAgrawal9265 commented
I have done changes which were suggested by you. Please have a look.

2020-10-23 19:37 UTC, suecarmol requested changes
Thanks for the changes made. I have one last request before I can approve this PR. Could you please add a test to check that the withdrawn application's status is changed to `Invalid`?

Let me know if you have any questions about how to test this code.

2020-10-23 19:51 UTC, YashAgrawal9265 commented
I don't know how to test this code, but I had check that code and it is working.
<img width="960" alt="2020-10-24" src="https://user-images.githubusercontent.com/69956695/97047758-0dc21400-1597-11eb-8f5e-c92b0c4d00c8.png">

When I withdraw the application, it status get changed

<img width="960" alt="2020-10-24 (1)" src="https://user-images.githubusercontent.com/69956695/97047836-2fbb9680-1597-11eb-9403-4fa8f51953e2.png">

2020-10-26 19:55 UTC, suecarmol commented
You can base your test on this test: https://github.com/WikipediaLibrary/TWLight/blob/master/TWLight/users/tests.py#L258

What you want to do is the following:

1. Create an application with a `PENDING` status.
2. Create request and response objects using the `WithdrawApplication` view. 
3. Assert that the application status changed from `PENDING` to `INVALID`.

Let me know if you have any more questions!

2020-10-27 17:41 UTC, YashAgrawal9265 commented
app8 = ApplicationFactory(
            status = Application.PENDING,
            editor=self.user_editor.editor,
        )

        factory = RequestFactory()
        request = factory.get(
            reverse("users:withdraw", kwargs={"pk": self.editor1.pk,"id"=self.app.pk})
        )
        request.user = self.user_editor
        response = views.WithdrawApplication.as_view()(request,pk=self.editor1.pk,id=self.app.pk)


Is this a right code for testing??

2020-10-29 00:24 UTC, suecarmol commented
> app8 = ApplicationFactory(
> status = Application.PENDING,
> editor=self.user_editor.editor,
> )
> 
> ```
>     factory = RequestFactory()
>     request = factory.get(
>         reverse("users:withdraw", kwargs={"pk": self.editor1.pk,"id"=self.app.pk})
>     )
>     request.user = self.user_editor
>     response = views.WithdrawApplication.as_view()(request,pk=self.editor1.pk,id=self.app.pk)
> ```
> 
> Is this the right code for testing??

It's looking good, although you don't need to pass the `editor.pk` parameter to the view. Add this code to the test file and run the tests. If it fails, try to figure out why. If you can't, let me know and I'll help you.

2020-10-29 02:59 UTC, YashAgrawal9265 commented
3.Assert that the application status changed from PENDING to INVALID.

What should I write in this step???

2020-10-29 13:50 UTC, YashAgrawal9265 commented
I have run the testcase it showing error.
<img width="960" alt="2020-10-29 (4)" src="https://user-images.githubusercontent.com/69956695/97582402-b4853500-1a1b-11eb-910b-278dd0b751fa.png">

2020-10-29 20:18 UTC, suecarmol commented
> 3.Assert that the application status changed from PENDING to INVALID.
> 
> What should I write in this step???

Assertions help prove that the code is behaving as expected. I would add one assertion at the beginning of the function to check that the application has a status of `PENDING` and after running the `WithdrawApplication` view, I would add an assertion to check that the status is `INVALID`. 

An assertion example is the following:

```python
# Add this assertion after you created app8 and before you run the WithdrawApplication view
self.assertEqual(app8.status, Application.PENDING)

# Add this assertion after you run the WithdrawApplication view
self.assertEqual(app8.status, Application.INVALID)
```

2020-10-29 20:20 UTC, suecarmol commented
> I have run the testcase it showing error.
> <img alt="2020-10-29 (4)" width="960" src="https://user-images.githubusercontent.com/69956695/97582402-b4853500-1a1b-11eb-910b-278dd0b751fa.png">

I think you need to replace `self.app.pk` with `app8.pk`. If this doesn't work, can you please commit your test code so I can take a look at it?

2020-10-30 02:54 UTC, YashAgrawal9265 commented
Now it is showing Assertion Error. I have commit my test code. Please have a look.

2020-11-02 19:19 UTC, suecarmol requested changes
I left a comment about the test you are writing. Also, the Travis CI build is failing due to a linting error. Please run `docker-compose exec twlight /venv/bin/black -t py37 /app/TWLight.` to format your code.

2020-11-02 19:19 UTC, suecarmol commented on TWLight/users/tests.py
> +
You need to add this new code in a new function, like

```python
def test_withdraw_application(self):
    # Insert code here
```

2020-11-02 19:39 UTC, YashAgrawal9265 commented
Again I get assertion error:

<img width="960" alt="2020-11-03 (1)" src="https://user-images.githubusercontent.com/69956695/97911350-1d98df80-1d71-11eb-805e-37081b96c679.png">

See my code:

<img width="960" alt="2020-11-03" src="https://user-images.githubusercontent.com/69956695/97911399-30abaf80-1d71-11eb-810b-53fddbde3fef.png">

2020-11-02 19:47 UTC, suecarmol commented
> Again I get assertion error:
> 
> <img alt="2020-11-03 (1)" width="960" src="https://user-images.githubusercontent.com/69956695/97911350-1d98df80-1d71-11eb-805e-37081b96c679.png">
> 
> See my code:
> 
> <img alt="2020-11-03" width="960" src="https://user-images.githubusercontent.com/69956695/97911399-30abaf80-1d71-11eb-810b-53fddbde3fef.png">

Try adding `app.refresh_from_db()` before `self.assertEqual(app.status, Application.INVALID)`

2020-11-05 04:32 UTC, YashAgrawal9265 commented
Finally, It has passed all the test cases. Now it is ready for merging.

2020-11-18 02:02 UTC, suecarmol requested changes
Thank you for your patience on this PR. You've done a great job! We need one more change before we can approve this.

2020-11-18 02:40 UTC, YashAgrawal9265 commented
I have done changes as you said.

2020-11-18 03:16 UTC, YashAgrawal9265 commented
Please can you tell me why Travis CI failed?
I have also run test.sh in my local, it has run all test without error.

2020-11-18 17:25 UTC, suecarmol requested changes
It looks like Travis CI failed on an unrelated error. Can you please make these last changes and upload them to see if Travis still fails?

2020-11-18 17:25 UTC, suecarmol commented on TWLight/users/templates/users/my_applications.html
> +{% comment %}Translators: Heading of the applications page where users can view all of their applications listed with
The indentation that was in this file before the last change you added was correct. Please change the indentation to the way it was before; it makes the code clearer and easier to read.

2020-11-18 19:22 UTC, YashAgrawal9265 commented
I have done change as you said.

2020-11-18 19:31 UTC, suecarmol approved these changes
Thank you for all the work and patience you put into this feature! This looks good to me!

2020-11-18 19:32 UTC, merged