Replace "stream" with "collection" in messages
WikipediaLibrary/TWLight pull request #621
Opened 2021-02-19 08:16 UTC by amire80

[//]: # (Thank you for uploading a PR to the Wikipedia Library!)

## Description
Describe your changes in detail following the [commit message guidelines](https://www.mediawiki.org/wiki/Gerrit/Commit_message_guidelines)

Replace "stream" with "collection" in messages

Also remove some '(s)' in parentheses in the same messages: it's not so necessary in English, and it's a bit confusing for translators.

## Rationale
[//]: # (Why is this change required? What problem does it solve?)

Make the text more consistent and easier to translate.

## Phabricator Ticket
[//]: # https://phabricator.wikimedia.org/T275040

2021-02-23 15:19 UTC, jsnshrmn requested changes
Hi there, and thanks for your work on this!
Unfortunately, you haven't caught all instances of `stream` that editors and coordinators see.
To catch them all, you'll need to search for the word stream across all project files and determine if each occurrence is something a person would see. For example, in the resources models:
https://github.com/WikipediaLibrary/TWLight/blob/master/TWLight/resources/models.py
there are several references to streams that coordinators would see (the help message, the validation error messages, etc). This was just a quick, non-exhaustive check, so you'll need to look for other examples.

2021-02-24 10:20 UTC, amire80 commented
Thanks for the review, @jsnshrmn.

My concern is mainly with the volunteer translators' comfort. I went over the messages that are _translatable_ in translatewiki, and I'm pretty sure that I caught them all, but please correct me if I'm wrong.

The strings in https://github.com/WikipediaLibrary/TWLight/blob/master/TWLight/resources/models.py appear to be internal and not translatable. Perhaps they are shown to developers or to API users, but not to end users. I'm not even sure they should be changed—maybe the word "stream" is correct for describing internal objects.

2021-02-24 21:01 UTC, jsnshrmn commented
Thank you for sharing your motivation for working on this issue. Please understand that when you are working on issues that we've identified, the scope of the issue may not perfectly align with your motivation for working on it. In this case, we've found that the word `stream` has been a point of confusion across the board, not just in public facing, translatable strings. It's undesirable for our internal team to be presented with different language for collections than what editors are presented with. Please include the requested changes. If there is some part of it there is giving you trouble, let us know and we'll try to help; if you are uninterested in working on it now that we've had this discussion, you are free to close this pr and unassign yourself from the task.
We really do appreciate the work you've done on this so far, though, and hope you can push through to completion.
Thanks!

2021-03-05 12:29 UTC, amire80 commented
I can try doing, but can this be done in several steps, with this patch being the first one? I am more certain about it, and it has immediate benefit to translators. I'll try changing the rest of the code later.

If you really want to do it in one big patch then I guess it can be closed.

2021-03-05 12:44 UTC, jsnshrmn commented
That is a reasonable request. The changes you have here are good, they just aren't enough to close out the task. We usually try to map PRs to tasks 1:1, but we can merge this in and make a note in phab that there's still work to do here.

2021-03-05 12:46 UTC, jsnshrmn approved these changes
This doesn't completely fix the issue, but it does reduce it. Thanks!

2021-03-05 12:46 UTC, merged

2021-03-05 13:02 UTC, amire80 commented
Thanks ❤️