Update 'Sent' status to 'Finalized'
WikipediaLibrary/TWLight pull request #728
Opened 2021-06-02 07:20 UTC by Shubh1815

[//]: # (Thank you for uploading a PR to the Wikipedia Library!)

## Description
Rename all strings and variables from 'sent' to 'finalized'. In the EMAIL distribution method case, we could still show users the 'sent to partner' text, and show 'finalized' otherwise.

## Rationale
[//]: # (Why is this change required? What problem does it solve?)

## Phabricator Ticket
[T237517](https://phabricator.wikimedia.org/T237517)

## How Has This Been Tested?
[//]: # (- Did you add tests to your changes? Did you modify tests to accommodate your changes?)
[//]: # (- Can this change be tested manually? How?)

## Screenshots of your changes (if appropriate):
[//]: # (It can also be a GIF to prove that your changes are working)

Partner with "Email" authorization method
![Screenshot_2021-06-02 The Wikipedia Library Card Platform(1)](https://user-images.githubusercontent.com/59529068/120439059-b4795900-c39f-11eb-83d1-2c3579532838.png)

Partner with "Access Codes" authorization method
![Screenshot_2021-06-02 The Wikipedia Library Card Platform](https://user-images.githubusercontent.com/59529068/120439063-b6dbb300-c39f-11eb-98a6-945d8a1068c1.png)

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Minor change (fix a typo, add a translation tag, add section to README, etc.)

2021-06-21 18:21 UTC, jsnshrmn requested changes
The code itself looks good, but please make the translation comments
here:
https://github.com/WikipediaLibrary/TWLight/blob/b5626ecef9315dbdc3809f75688c6e4ab3c00ff3/TWLight/applications/models.py#L166
and here:
https://github.com/WikipediaLibrary/TWLight/blob/b5626ecef9315dbdc3809f75688c6e4ab3c00ff3/TWLight/applications/models.py#L61

more clearly differentiated for the translators. Thanks!

2021-07-19 10:25 UTC, Samwalton9 commented
@Shubh1815 Can we do anything else to help you with this?

2021-07-20 15:46 UTC, jsnshrmn commented
Since this has been sitting for a while, I've gone ahead and made the change to get this mergable.

2021-07-20 15:56 UTC, jsnshrmn approved these changes

2021-07-20 15:56 UTC, merged