fix horizontal scroll bar
WikipediaLibrary/TWLight pull request #805
Opened 2021-09-05 11:24 UTC by akayjoshi

## Description
In My Library, there is a small amount of white space that causes a horizontal scroll bar. it should not display that horizontal scroll bar so the library fits the screen 100%.

## Phabricator Ticket
  https://phabricator.wikimedia.org/T289256

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Minor change (fix a typo, add a translation tag, add section to README, etc.)

2021-09-08 22:34 UTC, suecarmol requested changes
Thank you for fixing this. Users that use The Wikipedia Library on their phones will appreciate it! One small addition you need to make for this PR is to add the `overflow-hidden` class to the `new-local-rtl.css` file: https://github.com/WikipediaLibrary/TWLight/blob/master/TWLight/static/css/new-local.rtl.css#L23. This class should only have `overflow: hidden` attribute.

2021-09-09 12:56 UTC, akayjoshi commented
Hi suecarmol, I have a quetion.  Do we need to add  ```overflow-hidden``` class  in /static/css/new-local.css  also.

2021-09-09 14:40 UTC, suecarmol commented
> Hi suecarmol, I have a quetion. Do we need to add `overflow-hidden` class in /static/css/new-local.css also.

No, I don't think that's necessary because the `overflow-hidden` exists in the bootstrap 4 css. It's funny that this class doesn't exist in the RTL bootstrap 4 version.

2021-09-09 17:01 UTC, akayjoshi commented
Hi suecarmol, I have pushed a new commit for this, thanks.

2021-09-09 23:22 UTC, suecarmol approved these changes
I have checked in RTL and LTR languages, and the horizontal scroll bar bug is fixed. Thank you for your contribution!

2021-09-09 23:23 UTC, merged

2021-09-09 23:32 UTC, akayjoshi commented
Thank you 😊.