Accounts-available-for-all-Partners-Displayed
WikipediaLibrary/TWLight pull request #895
Opened 2021-11-28 07:23 UTC by amrit-srivastava

[//]: # (Thank you for uploading a PR to the Wikipedia Library!)

## Description
Accounts available for all type of partners are displayed under the partner name in each application.

## Phabricator Ticket
https://phabricator.wikimedia.org/T262164

## How Has This Been Tested?
Tested with 'python manage.py test' command. 

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Minor change (fix a typo, add a translation tag, add section to README, etc.)

2021-11-29 17:19 UTC, jsnshrmn requested changes
@amrit-srivastava This looks like a fine change at first glance, but I see that you stripped out portions of the PR template. Those sections are there because we need the requested information. How have you tested this change? Can you include a screenshot of a non-proxy partner with available account count?

2021-11-30 10:51 UTC, amrit-srivastava commented
Hi @jsnshrmn. Sorry for the inconvenience, I have updated the PR template.

2021-12-03 19:01 UTC, jsnshrmn approved these changes

2021-12-03 19:02 UTC, merged

2021-12-03 19:02 UTC, jsnshrmn commented
No problem; thanks for your work!

2021-12-04 06:02 UTC, amrit-srivastava commented
My pleasure :)