Added Login button to pages without one
WikipediaLibrary/TWLight pull request #974
Opened 2022-03-14 11:50 UTC by Ankit-Gupta18

[//]: # (Thank you for uploading a PR to the Wikipedia Library!)

## Description
Describe your changes in detail following the [commit message guidelines]Some pages on The Wikipedia Library are viewable by users who aren't logged in, but there are no obvious ways for them to initiate the login process.

When the user isn't logged in, the header should have a blue button (like the one used for linking to a logged in user's profile) at the right end which says 'Login' and will initiate the login sequence. Users should be redirected back to the page they were on.

## Rationale
[//]: # (Why is this change required? What problem does it solve?)

## Phabricator Ticket
[//]: # https://phabricator.wikimedia.org/T299638

## How Has This Been Tested?
This issue has been tested locally on by going to the page that is accessissible without logging in and observing the changes there.
Eg link - http://localhost/password/reset/

## Screenshots of your changes (if appropriate):
![45](https://user-images.githubusercontent.com/72732381/161054285-ac76aa90-8eb1-4915-a2ee-6ae56e266143.png)

## Types of changes
What types of changes does your code introduce? Add an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Minor change (fix a typo, add a translation tag, add section to README, etc.)

2022-03-14 15:25 UTC, Ankit-Gupta18 commented
Hi @suecarmol ,
Please review this PR too.
Thanks.

2022-03-24 23:31 UTC, suecarmol requested changes
Thank you for working on this. I have several comments about this PR:

1. You should add a screenshot to prove that the changes in your PR work as expected. If you check your changes locally, you would see that your code as-is does not work.
2. Fill in the section on how to test your changes.
3. Please make the changes requested.

Thanks in advance!

2022-03-24 23:31 UTC, suecarmol commented on TWLight/templates/header_partial_b4.html
> +            <li role="presentation" class="mobile-menu align-middle nav-item">
This tag does not have a closing tag

2022-03-24 23:31 UTC, suecarmol commented on TWLight/templates/header_partial_b4.html
> +              <a class="btn twl-btn" href="{% url 'oauth_login' %}?next={{request.path}}">
This tag does not have a closing tag

2022-03-24 23:31 UTC, suecarmol commented on TWLight/templates/header_partial_b4.html
> +              <a class="btn twl-btn" href="{% url 'oauth_login' %}?next={{request.path}}">
Please add a `trans` Django element with `Log In` as its text. See the Log out button as an example.

2022-03-24 23:31 UTC, suecarmol commented on TWLight/templates/header_partial_b4.html
> +          {% elif not user.is_authenticated %}
Change this to `{% else %}`

2022-03-24 23:32 UTC, suecarmol commented on TWLight/templates/header_partial_b4.html
> +              <a class="btn twl-btn" href="{% url 'oauth_login' %}?next={{request.path}}">
Also add a `{% comment %}` for translators

2022-03-31 12:43 UTC, Ankit-Gupta18 commented
Hi @suecarmol ,
I have addressed all the reviews. Please check it

2022-04-01 00:55 UTC, suecarmol approved these changes
Thank you for your work on this!

2022-04-01 00:55 UTC, merged